# Generated by Django 6.0.3 on 2026-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Tumer', models.CharField(choices=[('beg', 'benign'), ('mal', 'malignant')], max_length=3)),
                ('image', models.ImageField(upload_to='b_type/')),
            ],
        ),
    ]
