# Generated by Django 6.0.3 on 2026-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
        migrations.AlterField(
            model_name='info',
            name='Tumer',
            field=models.CharField(max_length=15),
        ),
    ]
